Update 7.c
TheAlgorithms/C pull request #1016
Opened 2022-10-09 05:57 UTC by adidubs

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-09 06:01 UTC, dubeyadi approved these changes

2022-10-09 06:02 UTC, dubeyadi approved these changes

2022-10-09 06:08 UTC, dubs25012002 approved these changes

2022-10-26 19:09 UTC, Panquesito7 reviewed
Could you explain the changes made in this file?

2022-11-14 05:42 UTC, xeland314 requested changes
Please fix the highlighted sections

2022-11-14 05:42 UTC, xeland314 commented on leetcode/src/7.c
> + int res=0;
Bad indentation.

2022-11-14 05:42 UTC, xeland314 commented on leetcode/src/7.c
> +    if(x > INT_MAX || x<(-INT_MAX)){
INT_MAX is undefined. Please add the header <limits.h>

2023-01-05 00:22 UTC, closed without merging