Create 2428.cpp
TheAlgorithms/C pull request #1019
Opened 2022-10-09 06:20 UTC by adidubs

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-09 06:25 UTC, dubs25012002 approved these changes

2022-10-09 06:26 UTC, dubs25012002 approved these changes

2022-10-09 07:08 UTC, mishraabhinn commented
Please read the contribution guidelines. This pr is not up to the standard we accept. Thanks. For any guidance, you can connect with us on discord and gittter.

2022-11-14 18:49 UTC, Panquesito7 requested changes
LeetCode problems should be made in C only.
Please port the problem to the C language.

If you need any help, let us know here or on our [**Discord server**](https://the-algorithms.com/discord)! 🙂

2023-01-04 00:21 UTC, closed without merging