Added leetcode problem 100
TheAlgorithms/C pull request #1026
Opened 2022-10-09 16:50 UTC by chandansahuji

#### Description of Change

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-09 19:42 UTC, hussainiftikhar5242 commented
please assign this task to me @chandansahuji . i can do it.

2022-10-10 13:23 UTC, chandansahuji commented
Hi @hussainiftikhar5242 ,its a PR(Pull Request),you can ask in the issues section ,to work on a particular issue.

2022-10-28 23:44 UTC, Panquesito7 requested changes
Please resolve the merge conflicts (for the `leetcode/README.md` file) [**here**]8https://github.com/TheAlgorithms/C/pull/1026/conflicts).
Let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord)! 🙂

2022-10-28 23:44 UTC, Panquesito7 commented on leetcode/src/100.c
> +#include <stdio.h>
Could you please add a small description of the problem?

2022-11-09 04:48 UTC, closed without merging