Added the program to calculate distance
TheAlgorithms/C pull request #1050
Opened 2022-10-15 17:41 UTC by ArnabNath1

#### Description of Change
I have made he program to calculate the distance between two points/

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-16 03:13 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, the documentation is not up to our [**standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). Please update the file accordingly. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 😃

2022-10-16 06:50 UTC, ArnabNath1 commented
What kind of changes do you want? Can you please explain it so that I can make the necessary changes?

2022-10-28 20:04 UTC, Panquesito7 requested changes
You can find more details on our [**contributing guidelines**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).

2022-10-28 20:04 UTC, Panquesito7 commented on geometry/distance.c
> +#include <stdio.h>
Please add a one-line description of what the library/header is for (**see the example below**).

```c
#include <stdio.h>      /// for IO operations
#include <assert.h>    /// for assert
```

2022-10-28 20:04 UTC, Panquesito7 commented on geometry/distance.c
> +float distance(int x1, int y1, int x2, int y2)
This should include parameter documentation, what does the function return, etc..

2022-10-28 20:04 UTC, Panquesito7 commented on geometry/distance.c
> + * Author Arnab Nath
Author fields should _always_ use Markdown formatting.

2022-10-28 20:04 UTC, Panquesito7 commented on geometry/distance.c
> + * The code is implemented in VS Code
You should explain what is the algorithm about, how it works, a Wikipedia link, space complexity, etc.. etc..

2022-12-25 00:23 UTC, closed without merging