add Online Stock Span
TheAlgorithms/C pull request #1142
Opened 2022-11-09 08:21 UTC by alexpantyukhin

#### Description of Change

Add a guide for new LeetCode solutions.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-11-10 01:20 UTC, Panquesito7 commented on leetcode/src/901.c
> +*/
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-11-15 09:24 UTC, alexpantyukhin commented
@Panquesito7 conflicts have been resolved. Please re-review

2022-11-16 00:29 UTC, Panquesito7 commented on leetcode/src/901.c
> + * stockSpannerFree(obj);
```suggestion
 * stockSpannerFree(obj);
 */
```

2022-11-16 16:12 UTC, Panquesito7 commented on leetcode/src/901.c
> +}
```suggestion
```

2022-11-16 16:13 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🚀

2022-11-23 17:45 UTC, tjgurwara99 requested changes

2022-11-23 17:45 UTC, tjgurwara99 commented on leetcode/src/901.c
> +// Keep the stack of monotonic inxrease price and index.
```suggestion
// Keep the stack of monotonically increasing price and index.

```

2022-11-24 20:54 UTC, tjgurwara99 approved these changes

2022-11-25 18:51 UTC, Panquesito7 approved these changes

2022-11-25 18:57 UTC, merged