add Minimum Number of Operations to Move All Balls to Each Box leetcode
TheAlgorithms/C pull request #1146
Opened 2022-11-16 18:52 UTC by alexpantyukhin

#### Description of Change

Add a guide for new LeetCode solutions.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-11-17 03:44 UTC, Panquesito7 commented on leetcode/src/1769.c
> +
```suggestion
```

2022-11-17 03:46 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🚀

2022-11-23 17:47 UTC, tjgurwara99 requested changes

2022-11-23 17:47 UTC, tjgurwara99 commented on leetcode/src/1769.c
> +int* minOperations(char * boxes, int* returnSize){
Could you make this more consistent?

Either 
```suggestion
int* minOperations(char* boxes, int* returnSize){
```
which is what I prefer or
```suggestion
int * minOperations(char * boxes, int * returnSize){

```

2022-11-23 20:39 UTC, alexpantyukhin commented
review notes are fixed

2022-11-23 20:42 UTC, alexpantyukhin commented
review notes are fixed

2022-11-24 21:06 UTC, tjgurwara99 approved these changes

2022-12-02 05:02 UTC, Panquesito7 approved these changes

2022-12-02 05:03 UTC, merged