add Maximize the Confusion of an Exam leetcode
TheAlgorithms/C pull request #1150
Opened 2022-11-18 20:50 UTC by alexpantyukhin

#### Description of Change

Add a guide for new LeetCode solutions.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-11-19 19:41 UTC, arnabpal2022 submitted a review, later dismissed
Great!! it's perfect

2022-11-21 15:48 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🚀

2022-11-24 20:59 UTC, tjgurwara99 requested changes

2022-11-24 20:59 UTC, tjgurwara99 commented on leetcode/src/2024.c
> +int getMaxLength(char * answerKey, char targetChar, int k){
```suggestion
int maximizeTarget(char * answerKey, char targetChar, int k){
```

I believe you're trying to maximise the number of `'T'` or `'F'` not "getting" the max length.

2022-11-24 21:17 UTC, tjgurwara99 approved these changes

2022-12-02 04:55 UTC, Panquesito7 approved these changes

2022-12-02 04:55 UTC, merged