Origin/test2
TheAlgorithms/C pull request #1154
Opened 2022-11-20 17:55 UTC by arnabpal2022

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-11-21 21:43 UTC, Panquesito7 commented on leetcode/src/100.c
> +
```suggestion
```

2022-11-21 21:43 UTC, Panquesito7 commented on leetcode/src/100.c
> +        return true;
```suggestion
    if (p == NULL && q == NULL) {
        return true;
    }
```

2022-11-21 21:43 UTC, Panquesito7 commented on leetcode/src/100.c
> +        return false;
```suggestion
        if (p->val == q->val && isSameTree(p->left, q->left) &&
            isSameTree(p->right, q->right)) {
            return true;
        }
        else {
            return false;
        }
    }
    else {
        return false;
    }
```

2022-11-23 10:54 UTC, hawkaii submitted a review, later dismissed
no issue seen by me .

2022-11-26 15:54 UTC, arnabpal2022 commented on leetcode/src/100.c
> +void printTreePreOrder(struct TreeNode *p)
yep we can skip it. good practice it would be.

2022-11-26 16:00 UTC, arnabpal2022 commented
Check it out guys. if wrong inform me.

2022-12-16 20:14 UTC, Panquesito7 approved these changes
Thanks! 🚀

2022-12-16 20:27 UTC, alexpantyukhin approved these changes

2022-12-16 20:32 UTC, alexpantyukhin commented on leetcode/src/100.c
> +    return (p->val == q->val && isSameTree(p->left, q->left) &&
we still have to check that `p` and `q` are not NULL before

2022-12-17 10:32 UTC, alexpantyukhin commented on leetcode/src/100.c
> +    return (p->val == q->val && isSameTree(p->left, q->left) &&
@arnabpal2022 I would probably use something like this:
```c
    // both NULL - nodes are equal this case.
    if (p == NULL && q == NULL) {
        return true;
    }

    // Just one of nodes is NULL. Nodes are not equal
    if (p == NULL || q == NULL){
        return false;
    }

    // Main condition that vals are equal, and recursive check.
    return p->val == q->val
           && isSameTree(p->left, q->left)
           && isSameTree(p->right, q->right);
```

2023-01-18 18:43 UTC, tjgurwara99 requested changes

2023-02-26 00:26 UTC, closed without merging