add LCS algorithm (dynamic programming approach)
TheAlgorithms/C pull request #1164
Opened 2022-11-26 00:50 UTC by itskurtz

#### Description of Change

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-11-27 16:33 UTC, Panquesito7 requested changes
Great work! 🚀

2022-11-27 16:33 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> + * @see dynamic_programming/lcs.c
`@see` is only used for other similar implementations within the code.
For example, a file named `quick_sort.cpp` mentions the `quick_sort_2.cpp` implementation.

2022-11-27 16:33 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> +#include <assert.h>
Please add a one-line description of what the library/header is for (**see the example below**).

```c
#include <stdio.h>     /// for IO operations
#include <assert.h>    /// for assert
```

2022-11-27 16:33 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> +void test(void) {
```suggestion
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2022-11-27 16:33 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> +	free(B);
```suggestion
	free(B);

	printf("All tests have successfully passed!\n");
```

2022-11-27 16:33 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> + * @brief [LCS](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) algorithm
```suggestion
 * @brief [Longest Common Subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) algorithm
```

2022-11-27 16:34 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> + * @brief Main function
```suggestion
 * @brief Main function
 * @param argc commandline argument count (ignored)
 * @param argv commandline array of arguments (ignored)
```

2022-11-28 05:21 UTC, Panquesito7 commented on dynamic_programming/lcs.c
> +	test();
```suggestion
	test();  // run self-test implementations
```

2022-11-28 21:28 UTC, Panquesito7 submitted a review, later dismissed
Awesome work. Thanks! 🚀

2022-12-09 14:30 UTC, tjgurwara99 approved these changes

2022-12-24 01:41 UTC, Panquesito7 approved these changes

2022-12-24 01:46 UTC, merged