add leetcode Find the Smallest Divisor Given a Threshold
TheAlgorithms/C pull request #1175
Opened 2022-12-09 07:14 UTC by alexpantyukhin

#### Description of Change

Add a guide for new LeetCode solutions.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-12-17 01:48 UTC, Panquesito7 requested changes

2022-12-17 01:48 UTC, Panquesito7 commented on leetcode/DIRECTORY.md
> +| 1283 | [Find the Smallest Divisor Given a Threshold]https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/description/)  | [C](./src/1283.c) | Medium      |
```suggestion
| 1283 | [Find the Smallest Divisor Given a Threshold]https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/description/)  | [C](./src/1283.c) | Medium       |
```

2022-12-30 05:36 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-01-18 19:58 UTC, tjgurwara99 approved these changes

2023-01-20 23:39 UTC, merged