add leetcode Difference Between Ones and Zeros in Row and Column
TheAlgorithms/C pull request #1183
Opened 2022-12-13 17:44 UTC by alexpantyukhin

#### Description of Change

Add a guide for new LeetCode solutions.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-12-24 01:29 UTC, Panquesito7 requested changes

2022-12-24 01:29 UTC, Panquesito7 commented on leetcode/DIRECTORY.md
> +| 2482 | [ Difference Between Ones and Zeros in Row and Column](https://leetcode.com/problems/difference-between-ones-and-zeros-in-row-and-column/description/)     | [C](./src/2482.c) | Medium     |
```suggestion
| 2482 | [Difference Between Ones and Zeros in Row and Column](https://leetcode.com/problems/difference-between-ones-and-zeros-in-row-and-column/description/)     | [C](./src/2482.c) | Medium     |
```

2022-12-29 06:41 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-01-18 18:56 UTC, tjgurwara99 approved these changes

2023-01-20 04:42 UTC, Panquesito7 approved these changes

2023-01-20 04:43 UTC, merged