feat: add bisection method
TheAlgorithms/C pull request #1233
Opened 2023-03-15 16:28 UTC by aybarsnazlica

#### Description of Change

Added bisection method used for root finding. 

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-03-16 15:50 UTC, aybarsnazlica commented on numerical_methods/bisection_method.c
> +        if (func(middle) == 0.0 || error < tolerance)
That's right. But I think that will hurt code readability.

2023-03-16 23:09 UTC, CascadingCascade reviewed
I would suggest you to replace all `float` with `double`, more precision wouldn't hurt

2023-03-16 23:09 UTC, CascadingCascade commented on numerical_methods/bisection_method.c
> +        if (sign(func(middle), func(x_left)) >= 0.0)
You probably shouldn't use `>=` here, `func(x_left)` simply can't be zero, and if `func(middle)` equals zero the function would have returned already.

2023-03-17 01:52 UTC, aybarsnazlica commented on numerical_methods/bisection_method.c
> +        float error = fabs(x_left - x_right) / 2;
I see. Changed to `middle - x_left`.

2023-03-17 02:13 UTC, aybarsnazlica commented on numerical_methods/bisection_method.c
> +#include <math.h>    /// for pow and fabs
Right. I kept fabs for the tests.

2023-03-17 05:22 UTC, alexpantyukhin submitted a review, later dismissed

2023-03-17 05:43 UTC, CascadingCascade submitted a review, later dismissed
LGTM

2023-03-17 18:03 UTC, Panquesito7 requested changes

2023-03-17 18:03 UTC, Panquesito7 commented on numerical_methods/bisection_method.c
> + * opposite signs. https://en.wikipedia.org/wiki/Bisection_method
```suggestion
 * @brief In mathematics, the [Bisection Method](https://en.wikipedia.org/wiki/Bisection_method) is a root-finding method that
 * applies to any continuous function for which one knows two values with
 * opposite signs.
```

2023-03-17 18:03 UTC, Panquesito7 commented on numerical_methods/bisection_method.c
> + * @param x
Undocumented parameter.

2023-03-18 03:13 UTC, aybarsnazlica commented on numerical_methods/bisection_method.c
> + * @param x
Added documentation.

2023-03-24 19:13 UTC, Panquesito7 commented on numerical_methods/bisection_method.c
> + * @returns `sign`
What is `sign` exactly? Please document this here.

2023-03-24 19:14 UTC, Panquesito7 commented on numerical_methods/bisection_method.c
> +#include <math.h>    /// for fabs
Needed for the `printf` function.
```suggestion
#include <math.h>    /// for fabs
#include <stdio.h>   /// for IO operations
```

2023-03-24 19:15 UTC, Panquesito7 commented on numerical_methods/bisection_method.c
> +           EPSILON);  // the algorithm works as expected
```suggestion
           EPSILON);  // the algorithm works as expected

           printf("All tests have successfully passed!\n");
```

2023-03-31 17:59 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-03-31 19:50 UTC, tjgurwara99 approved these changes

2023-04-01 14:23 UTC, alexpantyukhin approved these changes

2023-04-05 22:02 UTC, merged