docs: fixed some documentation errors in BLAKE2b
TheAlgorithms/C pull request #1234
Opened 2023-03-19 08:36 UTC by dsmurrow

#### Description of Change

Removed doc comments describing include's as they seemed to mess up the doc generation. Also removed the define specifier in doc comments as Doxygen couldn't seem to parse them.

#### Checklist

- [x] Added description of change
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

2023-03-19 17:55 UTC, alexpantyukhin submitted a review, later dismissed

2023-03-24 19:22 UTC, Panquesito7 commented on hash/hash_blake2b.c
> +#include <assert.h>    // for asserts
Please add back the 3rd slash for all of the headers/libraries.

2023-03-31 18:12 UTC, Panquesito7 requested changes

2023-03-31 18:12 UTC, Panquesito7 commented on math/euclidean_algorithm_extended.c
> +/**
Please remove this file from the PR (it appears you already have a PR for this).

2023-03-31 18:12 UTC, Panquesito7 commented on hash/hash_blake2b.c
> +    uint8_t key[64] = {
Please add all of the tests in a separate test function to keep `main` clean.

2023-04-05 17:14 UTC, Panquesito7 commented on hash/hash_blake2b.c
> +    printf("all tests have successfully passed!\n");
```suggestion
    printf("All tests have successfully passed!\n");
```

2023-04-05 17:15 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-04-06 11:58 UTC, alexpantyukhin approved these changes

2023-04-07 19:35 UTC, merged