feat: added extended Euclidean algorithm
TheAlgorithms/C pull request #1238
Opened 2023-03-25 00:26 UTC by dsmurrow

#### Description of Change

euclidean_algorithm_extended.c is implemented and lives in the math subdirectory.

In addition to finding the greatest common divisor of integers a and b, this algorithm will find values x and y such that $ax+by=gcd(a,b)$.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: added extended Euclidean algorithm

2023-03-31 18:02 UTC, Panquesito7 requested changes

2023-03-31 18:02 UTC, Panquesito7 commented on math/euclidean_algorithm_extended.c
> + * Both x and y are found by taking their value from 2 iterations ago minus the
```suggestion
 * @details Both x and y are found by taking their value from 2 iterations ago minus the
```

2023-03-31 18:02 UTC, Panquesito7 commented on math/euclidean_algorithm_extended.c
> + *
Missing parameter documentation.

2023-03-31 18:02 UTC, Panquesito7 commented on math/euclidean_algorithm_extended.c
> + *
No parameter documentation.

2023-04-07 18:36 UTC, Panquesito7 approved these changes
Great work! Thanks for contributing. 🚀

2023-04-12 15:16 UTC, tjgurwara99 approved these changes

2023-04-13 21:33 UTC, merged