merge sort added more efficient
TheAlgorithms/C pull request #1296
Opened 2023-08-16 12:22 UTC by BamaCharanChhandogi

#### Description of Change

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-08-16 12:25 UTC, BamaCharanChhandogi commented
hey! @pankajc007 could you check?

2023-08-19 05:15 UTC, realstealthninja requested changes

2023-08-19 05:15 UTC, realstealthninja commented on sorting/merge_sort.c
> - * @brief Implementation of [merge
please restore these lines

2023-08-19 05:15 UTC, realstealthninja commented on sorting/merge_sort.c
>  #include <stdlib.h>
```suggestion
#include <assert.h> /// For assert
#include <stdio.h> /// For I/O operations
#include <stdlib.h> /// For memory operations
```

2023-08-19 05:15 UTC, realstealthninja commented on sorting/merge_sort.c
> +// Function to merge two sorted subarrays into one sorted array
please follow proper documentation guidelines

2023-09-12 17:38 UTC, vil02 commented on sorting/merge_sort.c
> +    int L[n1], R[n2];
`ISO C++ forbids variable length array` - I think you should use `malloc` here (and of course `free` later).

2023-10-02 06:58 UTC, closed without merging