Added radix_sort_3.c
TheAlgorithms/C pull request #1317
Opened 2023-10-01 08:12 UTC by debnath003

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-10-01 08:16 UTC, debnath003 commented
@Panquesito7 @tjgurwara99 @alexpantyukhin could you all please approve my PR?

2023-10-01 09:33 UTC, tjgurwara99 commented
Please don't tag people directly unless you're stuck somewhere and it's very urgent. This does not qualify for urgent - people here are volunteering their time, so we will get to it when we get some time. Thanks.

2023-10-02 09:47 UTC, debnath003 commented
I have submitted my PR request @Panquesito7 @alexpantyukhin , awaiting review

2023-10-03 12:17 UTC, debnath003 commented
@Panquesito7  @tjgurwara99 @alexpantyukhin could you all please approve my PR? It has been a long time since I submitted my PR

2023-10-12 16:16 UTC, debnath003 commented
@Panquesito7 @tjgurwara99 @alexpantyukhin could you all please approve my PR? It has been a long time since I submitted my PR

2023-10-13 09:39 UTC, tjgurwara99 requested changes

2023-10-13 09:39 UTC, tjgurwara99 commented on sorting/radix_sort_3.c
> +
This needs to go inside its own `test` functions. Please read out [contribution guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#test) for guidance of what is expected of your PR.

2023-10-13 19:35 UTC, debnath003 commented
@tjgurwara99 Rectified the code by given `test()` function, please review this!

2023-11-21 00:22 UTC, closed without merging