Create XOR_linked_list.c
TheAlgorithms/C pull request #1362
Opened 2023-10-26 08:46 UTC by SahilK-027

#### Description of Change
Create  XOR_linked_list.c

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-11-27 14:43 UTC, realstealthninja requested changes
Very nicely done

2023-11-27 14:43 UTC, realstealthninja commented on data_structures/linked_list/XOR_linked_list.c
> +/**
this should go before the inclusion of files

2023-11-27 14:43 UTC, realstealthninja commented on data_structures/linked_list/XOR_linked_list.c
> + */
```suggestion
```

2023-11-27 14:43 UTC, realstealthninja commented on data_structures/linked_list/XOR_linked_list.c
> +#include <assert.h> /// to verify assumptions made by the program and print a diagnostic message if this assumption is false.
```suggestion
/**
 * @file
 *
 * @brief
 * [XOR List](https://en.wikipedia.org/wiki/XOR_linked_list) combines the properties of a 
 * circular doubly linked list and XOR pointers to save memory and enhance performance. 
 * Each node contains an XOR of the addresses of the previous and next nodes.
 *
 * In this implementation, functions to insert at the head, delete the first node, display list, get
 * list size, and get element at index functions are coded.
 *
 * @author [Sahil Kandhare](https://github.com/SahilK-027)
 */
#include <assert.h> /// to verify assumptions made by the program and print a diagnostic message if this assumption is false.
```

2023-11-27 15:36 UTC, SahilK-027 commented
Are the changes fine?

2024-01-02 06:27 UTC, realstealthninja approved these changes
LGTM

2024-01-10 00:22 UTC, closed without merging