feat: add binary gcd algorithm
TheAlgorithms/C pull request #1376
Opened 2023-12-02 16:06 UTC by tolis-0

#### Description of Change
Introduced an implementation of the binary GCD algorithm

#### References

#### Checklist
- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-01-02 06:16 UTC, realstealthninja requested changes

2024-01-02 06:16 UTC, realstealthninja commented on math/binary_gcd.c
> +unsigned long binary_gcd(unsigned long u, unsigned long v)
```suggestion
uint64_t binary_gcd(uint64_t u, uint64_t v)
```

2024-01-02 06:16 UTC, realstealthninja commented on math/binary_gcd.c
> +    unsigned long tmp;
```suggestion
    uint64_t tmp;
```

2024-01-02 06:16 UTC, realstealthninja commented on math/binary_gcd.c
> +#include <stdlib.h>
```suggestion
#include <stdlib.h>
#include <stdint.h>
```

2024-01-02 06:16 UTC, realstealthninja commented on math/binary_gcd.c
> +#include <stdlib.h>
dont recall if this is necessary @Panquesito7

2024-01-10 00:22 UTC, closed without merging

2024-01-10 12:47 UTC, tolis-0 commented
@realstealthninja I committed the changes.