feat:Add Polynomial Addition
TheAlgorithms/C pull request #600
Opened 2020-09-04 12:03 UTC by Ankita19ms0010

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-09-04 14:43 UTC, kvedala commented on data_structures/poly_add.c
> +struct term {
Structures should be documented as such:
```c
/**
 * @brief identifier for single-variable polynomial coefficients as a linked list
 */
struct term {
     double coef; /**< coefficient value */
     int pow;         /**< power of the polynomial term */
     struct term *next; /**< pointer to the successive term */
 };
```

2020-09-05 23:46 UTC, Panquesito7 requested changes

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> +void test1(struct term *poly1, struct term *poly2, struct term *poly3)
```suggestion
static void test1(struct term *poly1, struct term *poly2, struct term *poly3)
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> +void test2(struct term *poly1, struct term *poly2, struct term *poly3)
```suggestion
static void test2(struct term *poly1, struct term *poly2, struct term *poly3)
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> +void test3(struct term *poly1, struct term *poly2, struct term *poly3)
```suggestion
static void test3(struct term *poly1, struct term *poly2, struct term *poly3)
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Test function 1
```suggestion
 * @brief Test function 1
 *
 * @details
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Resultant polynomial is 7 x^3 + 5 x^2 + 12 x^1 + 12 x^0
```suggestion
 * Resultant polynomial is 7 x^3 + 5 x^2 + 12 x^1 + 12 x^0
 * @returns void
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Test function 2
```suggestion
 * @brief Test function 2
 *
 * @details
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Resultant polynomial is 5 x^5 + 1 x^4 + 5 x^3 + 5 x^1 + 7 x^0
```suggestion
 * Resultant polynomial is 5 x^5 + 1 x^4 + 5 x^3 + 5 x^1 + 7 x^0
 * @returns void
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Test function 3
```suggestion
 * @brief Test function 3
 *
 * @details
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Resultant polynomial is -7 x^0 + -5 x^1 + 7 x^3
```suggestion
 * Resultant polynomial is -7 x^0 + -5 x^1 + 7 x^3
 * @returns void
```

2020-09-05 23:46 UTC, Panquesito7 commented on data_structures/poly_add.c
> + * Main function
```suggestion
 * @brief Main function
 * @returns 0 on exit
```

2020-09-06 17:53 UTC, Panquesito7 requested changes

2020-09-06 17:53 UTC, Panquesito7 commented on data_structures/poly_add.c
> +			printf(" + ");
```suggestion
		if(poly != NULL) {
			printf(" + ");
		}
```

2020-09-06 18:06 UTC, Panquesito7 approved these changes
LGTM. 👍 😄

2020-09-09 14:02 UTC, kvedala commented
Please move the file to `misc` folder using the command:
```sh
$ git mv data_structures/poly_add.c misc/poly_add.c
$ git commit -m "file path fixed"
$ git push
```

2020-09-09 16:54 UTC, kvedala requested changes
All `temp` variable pointers with dynamically allocated memories must be freed. For example, line# 123 where new memory is incrementally allocated, is not freed before the function returns. Also, in `test` function, the dynamic memory allocated by the create_polynomial needs to be deallocated. 

Moreover, the deallocated by calling `free(poly1)` in main function is incorrect as it does not deallocate the memory of the chain. A simple solution would be to reverse the `create_polynomial` and deallocate memory in a chain:
```c
void free_poly(struct term* poly)
{
    if(!poly) /* NULL pointer does not need delete */
        return;
    free(poly->next);  /* ensure that next linked term is also deleted -> this will lead to recursive deletions as required. */
    free(poly); /* delete the current term */
}
```

2020-09-18 13:26 UTC, Ankita19ms0010 commented
@Panquesito7 , this pull request has been inactive for a few days now. Any additional changes?

2020-09-18 17:22 UTC, Panquesito7 approved these changes
Looks good to me, good work. 👍
It seems @kvedala has been inactive for more than a week.

2020-09-18 17:23 UTC, merged