Added octal to binary conversion
TheAlgorithms/C pull request #629
Opened 2020-10-01 11:52 UTC by vishnu0pothan

#### Description of Change

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-01 17:24 UTC, Panquesito7 requested changes

2020-10-01 17:24 UTC, Panquesito7 commented on conversions/octal_to_binary.c
> + * @author Vishnu P(https://github.com/vishnu0pothan)
```suggestion
 * @author [Vishnu P](https://github.com/vishnu0pothan)
```

2020-10-01 17:24 UTC, Panquesito7 commented on conversions/octal_to_binary.c
> +int main()
```suggestion

/**
 * @brief Main function
 * @returns 0 on exit
 */
int main()
```

2020-10-01 17:24 UTC, Panquesito7 commented on conversions/octal_to_binary.c
> +//This function converts octal number to binary number
A function should be documented like:

```c++
/**
 * @brief description of what the function does
 * @param <parameter name> description
 * @returns description
 */
```

2020-10-02 04:25 UTC, vishnu0pothan commented
Updated the function description. Changes made.

2020-10-02 04:26 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/vishnu0pothan/C/actions

2020-10-02 04:49 UTC, vishnu0pothan commented
Enabled the Actions

2020-10-02 05:08 UTC, Panquesito7 commented
Awesome, good work. To trigger the GitHub Actions, make a small commit. For example, remove line 61.
Next, we will see a commit made by the GitHub Actions updating `DIRECTORY.md`. 🙂

2020-10-02 05:14 UTC, vishnu0pothan commented
Done @Panquesito7 .

2020-10-02 05:16 UTC, Panquesito7 approved these changes
LGTM, good work. 😄 👍

2020-10-02 05:21 UTC, Panquesito7 commented
> This pull request **introduces 1 alert** when merging [d57edeb](https://github.com/TheAlgorithms/C/commit/d57edebc47fb596866c801b9b3ef750fa80b982f) into [d3bb124](https://github.com/TheAlgorithms/C/commit/d3bb124b90f3f7aaa404ea1e59d21d6e667d64b7) - [view on LGTM.com](https://lgtm.com/projects/g/TheAlgorithms/C/rev/pr-13cbbce10bcdc18a257ea5cff82a87c058f226eb)
> 
> **new alerts:**
> 
> * 1 for Multiplication result converted to larger type

Please fix the [warning](https://lgtm.com/projects/g/TheAlgorithms/C/rev/pr-13cbbce10bcdc18a257ea5cff82a87c058f226eb) reported by LGTM.

2020-10-02 12:16 UTC, merged