Create Queue Implementation using Linked List
TheAlgorithms/C pull request #720
Opened 2020-10-25 13:42 UTC by saumyasingh048

#### Description of Change
I have provided algorithm for implementation of queue using Linked List.

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-26 13:54 UTC, hemanth-kotagiri requested changes
Please add the ``.c`` file extension also for the file. It is missing. Take note of the warnings that I have commented earlier as well.

2020-10-26 13:54 UTC, hemanth-kotagiri commented on data_structures/linked_list/Queue Implementation using Linked List
> +            return q;
There is a potential warning in your code.
```In function ‘search’:
warning: returning ‘queue *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
   73 |             return q;
```
Please look into it.

2020-10-26 15:02 UTC, saumyasingh048 commented
I’ve made the changes and made the pull request once again . Kindly look into it now .


Sent from Yahoo Mail for iPhone


On Monday, October 26, 2020, 7:24 PM, Hemanth Kotagiri <notifications@github.com> wrote:




@hemanth-kotagiri requested changes on this pull request.

Please add the .c file extension also for the file. It is missing. Take note of the warnings that I have commented earlier as well.

In data_structures/linked_list/Queue Implementation using Linked List:
> +    queue *q;
+    q = p->front;
+    while(q != NULL)
+    {
+        printf("%d\n", q->data);
+        q = q->next;
+    }
+}
+int search(Q *p, int item)
+{
+    queue *q;
+    q = p->front;
+    while(q != NULL)
+    {
+        if(q->data == item)
+            return q;

There is a potential warning in your code.
warning: returning ‘queue *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
   73 |             return q;

Please look into it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-26 16:24 UTC, hemanth-kotagiri requested changes
Here are a few suggestions @saumyasingh048 .
1. **Always compile** the code that you write and check for errors/warnings and **fix them beforehand**.
2. Please **maintain spacing** between functions/chunks of code and **follow the official style guide**.
3. Please remove the redundant file of which I have left a comment on.

2020-10-26 16:24 UTC, hemanth-kotagiri commented on data_structures/linked_list/QueueLinkedList.c
> +}queue;
Please maintain spacing between chunks of code. It is important to have the code well structured.

2020-10-26 16:24 UTC, hemanth-kotagiri commented on data_structures/linked_list/QueueLinkedList.c
> +    printf("Element NOT Found.");
The non-void function that you have written here doesn't always return a value in all control paths. Please fix this issue.

2020-10-26 16:24 UTC, hemanth-kotagiri commented on data_structures/linked_list/QueueLinkedList.c
> +                queue item_loc = search(&q, item);
There is an error in your code here. Please fix it.
```In function ‘main’:
error: invalid initializer
Line 123 |    queue item_loc = search(&q, item);
```

2020-10-26 16:24 UTC, hemanth-kotagiri commented on data_structures/linked_list/QueueLinkedList.c
> +#include<stdio.h>
My humble request is that you please compile the code that you write before pushing it to this PR. I am finding compile-time errors/warnings which you can fix beforehand.

2020-10-26 19:39 UTC, hemanth-kotagiri commented
@saumyasingh048, if you would like to stick to the PR: #724 , please close this to avoid redundant PRs.

2020-10-31 06:50 UTC, hemanth-kotagiri commented
@Panquesito7 Can you please close this PR because another PR from the same user is raised: #724

2020-11-01 20:27 UTC, Panquesito7 commented
> close this PR

I'll close the other PR; this one is older than #724.

2020-11-02 11:18 UTC, hemanth-kotagiri commented
@Panquesito7 

Also, are you open for collaboration? I would love to join to review PRs, issues and contribute! 

Thanks!

2020-11-04 00:39 UTC, Panquesito7 commented
> would love to join to review PRs, issues and contribute

Keep contributing, project maintainers will later decide if you are capable to join the team. 🙂
For now, you can do the following in the [C-Plus-Plus](https://github.com/TheAlgorithms/C-Plus-Plus) and [C](https://github.com/TheAlgorithms/C) repositories:

- Review pull requests often.
- Watch the repository to get latest notifications.
- Fix errors or improve code/documentation via PR's.
- And much more you can do to help.

If you have any other questions, you can
[contact me](https://github.com/Panquesito7#contact) or other project maintainers.

Good to know you're interested in contributing! Thank you. 😃

2020-11-06 15:37 UTC, hemanth-kotagiri reviewed
@Panquesito7, you can remove this redundant PR as well adding the labels ``duplicate``, ``invalid`` as you did for #724 .

Thanks!

2020-11-06 21:51 UTC, closed without merging