Game of Life
TheAlgorithms/C pull request #808
Opened 2021-03-05 08:49 UTC by khod-naderi

#### Description of Change

#### References
Add Game of Life to game

#### Checklist

- [x] Added description of change
- [x] Added file name matches [game_of_life](https://github.com/khod-naderi/C/blob/master/games/game_of_life.c)
- [x] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-03-05 13:20 UTC, ayaankhan98 reviewed
please update the documentation according to doxygen documentation guidelines.

2021-03-05 15:29 UTC, khod-naderi commented
Excuse me, my English servant is not good, if you can say it easier

2021-03-05 18:08 UTC, Panquesito7 requested changes
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

2021-03-06 16:12 UTC, khod-naderi commented
I added a description to the code, is there still a problem?

2021-03-07 20:35 UTC, Panquesito7 requested changes
👍 Good code.

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * @returns 0 on clean exit.
```suggestion
 * @brief Main function.
 * @returns 0 on exit
```

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * em program function.
Please add a proper function description.

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * @returns char pointer new generation on clean exit.
Missing `world` parameter documentation.

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * draw program function. (void)
Please add a proper function description.

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * draw program function. (void)
Missing `world` parameter documentation.

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +* @file game_of_life.c
```suggestion
 * @file
```

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +* Conway's Game of Life
```suggestion
 * @brief [Game of life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)
 * implementation
 *
 * @details The Game of Life, also known simply as Life, is a cellular automaton devised by the British
 * mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined
 * by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial
 * configuration and observing how it evolves. It is Turing complete and can simulate a universal constructor or any other Turing machine.
```

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +* @author [Conway](https://en.wikipedia.org/wiki/John_Horton_Conway)
The `@author` is for those who made the file (you).
```suggestion
```

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +* @author [ali naderi](github.com/khod-naderi)
```suggestion
 * @author [Ali Naderi](https://github.com/khod-naderi)
```

2021-03-07 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +* It has a general array called world, which is the game world in which cells live
```suggestion
```

2021-03-10 01:47 UTC, Panquesito7 commented on games/game_of_life.c
> + * @file
```suggestion
```

2021-03-10 01:47 UTC, Panquesito7 commented on games/game_of_life.c
> +/**
```suggestion
/**
 * @file
```

2021-03-10 10:09 UTC, khod-naderi commented
I fix warning on Ubuntu, Mac and Windows

2021-03-10 18:15 UTC, Panquesito7 requested changes
Please address **all** the unresolved conversations above.

2021-03-11 08:36 UTC, khod-naderi commented on games/game_of_life.c
> +#include <unistd.h> // for sleep (usleep)
I do not speak English, i explain why I imported these header/library ?

2021-03-11 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> +#include <unistd.h> // for sleep func (usleep)
```suggestion
#include <stdio.h>     /// standard input/output
#include <stdlib.h>    /// to genrate random number AND memory management 
#include <time.h>      /// get time system for seed random number
#include <unistd.h>    /// for sleep func (usleep)
```

2021-03-11 20:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * For Show the world
Please add proper documentation. See #797 as a reference. Check other parts of the code, too.

2021-03-14 19:34 UTC, Panquesito7 requested changes

2021-03-14 19:34 UTC, Panquesito7 commented on games/game_of_life.c
> + * draw program function. (void)
Please add a proper function description.

2021-03-14 19:34 UTC, Panquesito7 commented on games/game_of_life.c
> + * For Show the world
Still not fixed.

2021-03-14 19:34 UTC, Panquesito7 commented on games/game_of_life.c
> + * @param world, pointer to world parameter
```suggestion
 * @param world pointer to world parameter
```

2021-03-14 19:34 UTC, Panquesito7 commented on games/game_of_life.c
> + * @param world, pointer to world parameter
```suggestion
 * @param world pointer to world parameter
```

2021-03-14 19:34 UTC, Panquesito7 commented on games/game_of_life.c
> + * em program function.
Still not fixed.

2021-04-21 17:35 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/khod-naderi/C/actions. **This is something that's required and mentioned in the contributing guidelines.**

2021-04-21 17:35 UTC, Panquesito7 commented on games/game_of_life.c
> +#include <stdlib.h>    /// to genrate random number AND memory management
```suggestion
#include <stdlib.h>    /// to generate random number AND memory management 
```

2021-04-21 17:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * @brief Function main.
```suggestion
 * @brief Main function
```

2021-04-21 17:35 UTC, Panquesito7 commented on games/game_of_life.c
> + * @returns 0 on Exit without error
```suggestion
 * @returns 0 on exit
```

2021-04-21 17:35 UTC, Panquesito7 commented on games/game_of_life.c
> +    */
```suggestion
    // The beginning of the eternal cycle of life
```

2021-04-21 17:35 UTC, Panquesito7 commented on games/game_of_life.c
> +        usleep(300000); // A short break = 0.03 sec
```suggestion
        draw(world);           /// Show the creatures of the world
        world = em(world);    /// Calculate the next generation
        usleep(300000);      /// A short break = 0.03 sec
```

2021-04-25 20:51 UTC, Panquesito7 requested changes
Please address **all** the unresolved conversations above (don't only click on `Resolve`, try to really resolve them).

2021-04-27 21:33 UTC, Panquesito7 requested changes
By addressing all the unresolved conversations, I didn't mean to only click on `resolve`: I also meant to try to fix them. Try to make your code as per our [guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Thank you.

2021-10-07 07:32 UTC, khod-naderi commented
I'm very sorry, my English was not good enough for effective communication

On Wed, Oct 6, 2021, 03:41 github-actions[bot] ***@***.***>
wrote:

> This pull request has been automatically marked as abandoned because it
> has not had recent activity. It will be closed if no further activity
> occurs. Thank you for your contributions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C/pull/808#issuecomment-935122428>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWQRUJZQNV2ZPS3S4BJTQLUFOH23ANCNFSM4YU2BSPQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-14 00:12 UTC, closed without merging