Exponential Search
TheAlgorithms/C pull request #818
Opened 2021-03-24 22:00 UTC by faridevnz

#### Description of Change
- added Exponential Search Algorithm

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: implementation of Exponential Search

2021-03-24 22:14 UTC, Panquesito7 requested changes
👍 Good work!
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/faridevnz/C/actions

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> + */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> + */
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +void test(void)
```suggestion
static void test()
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +int main(void)
```suggestion
int main()
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    while ( upper_bound <= length && arr[upper_bound] < n ) upper_bound = upper_bound * 2;
```suggestion
    while ( upper_bound <= length && arr[upper_bound] < n ) { upper_bound = upper_bound * 2; }
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    if ( upper_bound > length ) upper_bound = length;
```suggestion
    if ( upper_bound > length ) { upper_bound = length; }
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    if ( l_index > r_index ) return -1;
```suggestion
    if ( l_index > r_index ) { return -1; }
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    if ( arr[middle_index] == n ) return middle_index;
```suggestion
    if ( arr[middle_index] == n ) { return middle_index; }
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +    if ( arr[middle_index] > n ) return binary_search(arr, l_index, middle_index-1, n); // left
```suggestion
    if ( arr[middle_index] > n ) { return binary_search(arr, l_index, middle_index-1, n); } // left
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Exponential%20Search.md
```suggestion
 *  \@brief [Exponential Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Exponential%20Search.md) implementation
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \author [Alessio Farinelli] (https://github.com/faridevnz)
```suggestion
 *  \author [Alessio Farinelli](https://github.com/faridevnz)
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +void test(void);
```suggestion
static void test();
```

2021-03-24 22:14 UTC, Panquesito7 commented on searching/exponential_search.c
> +#include <assert.h>
```suggestion
#include <assert.h>   /// for assert
```

2021-03-24 22:52 UTC, Panquesito7 requested changes

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \@brief [Exponential Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Exponential%20Search.md)
```suggestion
 *  \brief [Exponential Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Exponential%20Search.md)
```

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \param arr:         array where search the element
```suggestion
 *  \param arr array where search the element
```

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \returns:           -1 if the element wasn't found
```suggestion
 *  \param length the total length of the given array (arr)
 *  \param n the element to find in the array (arr)
 * 
 *  \returns the index of the element (n) in the array (arr)
 *  \returns -1 if the element wasn't found
```

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \returns:           -1 if the n element wasn't found
```suggestion
 *  \param arr array where search the element
 *  \param l_index start index of the array (arr) to apply the algorithm
 *  \param r_index end index of the array (arr) to apply the algorithm
 *  \param n the element to find in the array (arr)
 * 
 *  \returns the index of the element (n) in the array (arr)
 *  \returns -1 if the n element wasn't found
```

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  Function: binary_search
Provide a brief description of what the function does or is for. For long/detailed description, use `\details`.

2021-03-24 22:52 UTC, Panquesito7 commented on searching/exponential_search.c
> +int binary_search(const int* arr, const int l_index, const int r_index, const int n);
Consider using `uint64_t`, `uint32_t`, `uint16_t`, or even `uint8_t` for non-negative values. For negative values, use `int64_t` or their appropriate size ([reference](https://en.cppreference.com/w/c/types/integer)). Requires the `inttypes.h` header. Check out other parts of the code, too. 🙂

2021-03-25 15:36 UTC, Panquesito7 requested changes
👍 Good work!

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> +#include <inttypes.h>  // for int64_t, uint16_t
```suggestion
#include <assert.h>      /// for assert
#include <inttypes.h>    /// for int64_t, uint16_t
```

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  [Binary Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Binary%20Search.md)
```suggestion
 *  the array using the [Binary Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Binary%20Search.md) algorithm
```

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  @returns 0 on exit
```suggestion
 * @brief Main function
 * @returns 0 on exit
```

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  @returns void
```suggestion
 * @brief Self-test implementations
 * @returns void
```

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> +
Add a one-line description of what the functions do (this should be a short description; see the example below).
```c++
static void test();  ///< used to run the self-test implementations
```

2021-03-25 15:36 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  Function: exponential_search
Add a brief description of what the function does (same in other parts of the code).

2021-03-25 16:28 UTC, Panquesito7 commented on searching/exponential_search.c
> + * @brief Main function that run the test
```suggestion
 * @brief Main function
```

2021-03-25 16:28 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  Function: exponential_search
There's a detailed description, but there's no brief description. 🙂

2021-03-25 16:28 UTC, Panquesito7 commented on searching/exponential_search.c
> + */
```suggestion
 * \details recursive function that take an array and quickly find the range 
 * where to apply the binary search algorithm to find the given element
 * ----------------------------
 * \param arr array where search the element
 * \param length the total length of the given array (arr)
 * \param n element to find in the array (arr)
 *
 * \returns the index of the element (n) in the array (arr)
 * \returns -1 if the element wasn't found
 */
```

2021-03-25 16:28 UTC, Panquesito7 commented on searching/exponential_search.c
> + *  \returns -1 if the n element wasn't found
```suggestion
 * Function: binary_search
 * \details recursive function that search the given element in
 * the array using the [Binary Search](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Search%20Algorithms/Binary%20Search.md)
 * ----------------------------
 * \param arr array where search the element
 * \param l_index start index of the array (arr) to apply the algorithm
 * \param r_index end index of the array (arr) to apply the algorithm
 * \param n element to find in the array (arr)
 *
 * \returns the index of the element (n) in the array (arr)
 * \returns -1 if the n element wasn't found
```

2021-03-25 17:09 UTC, Panquesito7 approved these changes
Amazing work, I like how you've made the code so well. 👍
Code and documentation are pretty good and refined; LGTM. 😄 🎉

2021-03-25 17:23 UTC, faridevnz commented
> Amazing work, I like how you've made the code so well. 👍
> 
> Code and documentation are pretty good and refined; LGTM. 😄 🎉
> 
> 

@Panquesito7 thanks a lot 😆 I will continue to contribute 🥳

2021-03-25 18:28 UTC, merged

2021-03-26 11:36 UTC, KirwinD commented
@faridevnz - great!

2021-03-26 11:40 UTC, faridevnz commented
> @faridevnz - great!

Thanks @KirwinD 😊