printf statement written in c (as minprintf) without using stdio.h li…
TheAlgorithms/C pull request #820
Opened 2021-03-28 15:47 UTC by Jaskarn7

…brary.

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-03-30 17:04 UTC, Panquesito7 requested changes
Documentation is not up to the [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html).
Please read them **carefully** and **follow them**.

2021-03-31 02:28 UTC, Panquesito7 requested changes
You can also see the [typical structure](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) to see how to make your program up to the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). 🙂

2021-03-31 03:09 UTC, Jaskarn7 commented
This is the first time i am doing open source , so please pardon me.

On Wed, 31 Mar 2021, 7:58 am David Leal, ***@***.***> wrote:

> *@Panquesito7* requested changes on this pull request.
>
> You can also see the typical structure
> <https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program>
> to see how to make your program up to the repository standards
> <https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md>. 🙂
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C/pull/820#pullrequestreview-624843286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATM37KNVM6GVKD7J26J5Y4LTGKCE7ANCNFSM4Z6E7VAA>
> .
>

2021-03-31 04:23 UTC, Panquesito7 commented
> This is the first time I am doing open source, so please pardon me.

It's alright! We're glad you decided to contribute to TheAlgorithms! 😃
Just make sure you follow the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). Thank you. 🙂

2021-03-31 18:59 UTC, Panquesito7 requested changes
👍 Well done!

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> +#define PRECISION_FOR_FLOAT 8
Avoid using global variables; they may cause overflows and other issues. Pass them as local function parameters or as struct members.

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> +int bufsize = 0;
Avoid using global variables; they may cause overflows and other issues. Pass them as local function parameters or as struct members.

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @return Ten to the power a.
```suggestion
 * @return Ten to the power a
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param a The power of ten which is to be returned.
Add a brief description of what the function does (use `@details` for a long description).

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @return 'true'(1) if character is a number else 'false'(0)
```suggestion
 * @return `true`(1) if the character is a number 
 * @return `false`(0) if the character is NOT a number
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param c number to be checked.
Is this a number or a character?
```suggestion
 * @param c number to be checked
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * Returns specific required next character.
```suggestion
 * @brief Returns specific required next character
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * Checks if a character is a number.
```suggestion
 * @brief Checks if a character is a number.
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> +int power_of_ten(int a)
Consider using `uint64_t`, `uint32_t`, `uint16_t`, or even `uint8_t` for non-negative values. For negative values, use `int64_t` or their appropriate size ([reference](https://en.cppreference.com/w/c/types/integer)). Requires the `inttypes.h` header. Check out other parts of the code, too. 🙂

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @return character at which p is pointing, if bufsize is zero.
```suggestion
 * @param p pointer to a format string of `minprintf()`
 * @return character inside the buffer, if `bufsize` is one
 * @return character at which p is pointing, if `bufsize` is zero
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> +		bufsize = 0; // Since character is used, this sets bufsize to zero.
```suggestion
		bufsize = 0; ///< Since character is used, this sets `bufsize` to zero.
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * Stores character to buffr.
```suggestion
 * @brief Stores character to the buffer
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param c Character to be stored in buffr.
```suggestion
 * @param c character to be stored in the buffer
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * Calculates number of digits in a number.
```suggestion
 * @brief Calculates the number of digits in a number
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @return number of digits in n.
```suggestion
 * @param n number whose digits are to be counted
 * @return number of digits in n
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param s character to be printed on screen.
```suggestion
 * @brief Prints one character on screen
 * @param s character to be printed on the screen
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param p pointer to string to be reversed.
```suggestion
 * @brief Reverses a string using two pointer algorithm
 * @param p pointer to string to be reversed
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param precision Total character of number to be printed (prints 0 before number if size of number < precision).
```suggestion
 * @brief The algorithm here is to first convert the number into a
 * string, and then reverse it by passing it to the `reverse_str` function,
 * and then printing it on the screen.
 * @param n Number to be printed
 * @param width Total characters to be printed (Prints ` ` if (size < width)
 * @param precision Total character of the number to be printed (prints 0 before the number if size of number < precision)
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param precision Tells number of digits to be printed after decimal (By default it is 8).
```suggestion
 * @brief The algorithm here is also the same as the `print_int_value` function.
 *
 * @details
 * First, the digits before decimal is printed by converting the double 
 * to int. Then after printed a `.`, the double number is subtracted with
 * the integer value of the number, leaving us with 0 before the decimal.
 * Then, we multiply the number with 10 raised to the power precision (
 * precision means how many digits to be printed after the decimal.)
 * By default, the precision is 8 if it is not specified.
 * Then, the remaining number is printed on the screen.
 * @param dval double number to be printed
 * @param width similar to width parameter of print_int_value()
 * @param precision tells the number of digits to be printed after the decimal (By default it is 8)
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @param precision Total charanters of string to be printed (Prints whole string if 0 or greater than size of string).
```suggestion
 * First size of the string is calculated to check whether
 * width and precision are to be taken into account or not
 * Then, the string is printed in accordingly.
 * @param p pointer to string to be printed
 * @param width if (width > sizeof string) then, blanks will be printed before sting to cover up the width
 * @param precision total characters of the string to be printed (prints the whole string if 0 or greater than size of string)
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @return character pointer to the current pointer of string p. (Used to update vaue of p)
```suggestion
 * @brief Takes width and precision specified from the format of the string.
 * @param p pointer of the format string
 * @param width variable in which width will be stored
 * @param precision variable in which precision will be stored
 * @return character pointer to the current pointer of string p (used to update value of p)
```

2021-03-31 18:59 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * minprintf is the main function.
The main function is **always** called `main` and is of `int` value (see the [typical structure](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program for more information).

2021-04-01 02:00 UTC, Panquesito7 reviewed
👍 Well done!
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Jaskarn7/C/actions

2021-04-01 02:00 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @brief Implementation of a function similar to printf
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2021-04-01 19:40 UTC, Panquesito7 reviewed
Change the file name to `min_printf.c`.

2021-04-01 19:40 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * Refer https://www.geeksforgeeks.org/variable-length-argument-c to know about it's basic structure
```suggestion
```

2021-04-01 19:40 UTC, Panquesito7 commented on developer_tools/minprintf.h
> + * @brief Implementation of a function similar to printf
```suggestion
 * @brief Implementation of a [function](https://www.geeksforgeeks.org/variable-length-argument-c) similar to `printf`
```

2021-04-02 02:09 UTC, Panquesito7 reviewed
As you can see in the [`developer_tools/malloc_dbg.c`](https://github.com/TheAlgorithms/C/blob/master/developer_tools/malloc_dbg.c) file, there's no `main` function (and that's correct), but, in the [`developer_tools/test_malloc_dbg.c`](https://github.com/TheAlgorithms/C/blob/master/developer_tools/test_malloc_dbg.c) file (which depends on the previous one), **does** have a `main` function. Could you do something similar, to test your program works properly? Thanks! 🙂

2021-04-02 02:09 UTC, Panquesito7 commented on developer_tools/min_printf.h
> +#include <stdarg.h> // For va_start and va_arg functions
```suggestion
#include <stdlib.h>   /// for `malloc` and `free` functions
#include <unistd.h>  /// for `write` function
#include <stdarg.h>  /// for `va_start` and `va_arg` functions
```

2021-04-02 02:09 UTC, Panquesito7 commented on developer_tools/min_printf.h
> +#define PRECISION_FOR_FLOAT 8
```suggestion
#define INT_MAX_LENGTH 10       /// used as standard length of string to store integers
#define PRECISION_FOR_FLOAT 8   /// default precision for float or double if not specified
```

2021-04-02 18:28 UTC, Panquesito7 requested changes
👍 Well done!

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> + * @return 0 on exit
```suggestion
 * @returns 0 on exit
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> +int main(void)
```suggestion
int main()
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> +}
```suggestion
}

```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> +    /*For testing to print strings */
```suggestion
    // print strings using `printf` and `min_printf`
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> +    /*For testing to print floats or doubles */
```suggestion
    // print floats or doubles using `printf` and `min_printf`
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/test_min_printf.c
> +    /* For testing to print integers */
```suggestion
    // print integers `printf` and `min_printf`
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/min_printf.h
> +*/
```suggestion
*/

#ifndef MIN_PRINTF_H
#define MIN_PRINTF_H
```

2021-04-02 18:28 UTC, Panquesito7 commented on developer_tools/min_printf.h
> +}
```suggestion
}

#endif /* MIN_PRINTF_H */
```

2021-04-03 00:33 UTC, Panquesito7 requested changes
👍 Amazing! Just a few minor things, and it's done.

2021-04-03 00:33 UTC, Panquesito7 commented on developer_tools/min_printf.h
> + * printf statement rewritten (as min_printf) in c without using stdio.h library
```suggestion
 * `printf` statement rewritten (as `min_printf`) in C without using the `stdio.h` library
```

2021-04-03 00:33 UTC, Panquesito7 commented on developer_tools/min_printf.h
> + * Syntax of min_printf is same as printf
```suggestion
 * Syntax of `min_printf` is same as `printf`
```

2021-04-03 00:33 UTC, Panquesito7 commented on developer_tools/min_printf.h
> + * The format specifiers and escape sequence is same as for printf
```suggestion
 * The format specifiers and escape sequence is the same as for `printf`
```

2021-04-03 00:33 UTC, Panquesito7 commented on developer_tools/min_printf.h
> + * User can also specify the width and precision if requires just like in the case of printf
```suggestion
 * User can also specify the width and precision if required, just like in the case of `printf`
```

2021-04-03 00:33 UTC, Panquesito7 commented on developer_tools/min_printf.h
> + * 	- Then type min_printf(), and pass required parameters to it
```suggestion
 * 	- Then type `min_printf()`, and pass required parameters to it
```

2021-04-03 00:44 UTC, Panquesito7 approved these changes
Amazing work; I like how you've made & improved the code so well. 😄 🎉
Code and documentation are pretty good and very refined; LGTM. 👍

2021-04-03 01:08 UTC, Jaskarn7 commented
Thanks bro, learned a lot about documentation working with you and
genuinely saying that was really great experience.

On Sat, Apr 3, 2021 at 6:14 AM David Leal ***@***.***> wrote:

> *@Panquesito7* approved this pull request.
>
> Amazing work; I like how you've made & improved the code so well. 😄 🎉
> Code and documentation are pretty good and very refined; LGTM. 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C/pull/820#pullrequestreview-627416495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATM37KOG4KEGUKGANU5HU2DTGZQHTANCNFSM4Z6E7VAA>
> .
>

2021-04-03 01:48 UTC, KirwinD commented
@Jaskarn7 Great work, coding champ of the week! Awesome job

2021-04-03 06:33 UTC, ayaankhan98 approved these changes
Nice! Thanks for your contribution @Jaskarn7

2021-04-03 06:33 UTC, merged