feat: Add floyd cycle-detection-algorithm to find duplicate number
TheAlgorithms/C pull request #844
Opened 2021-07-21 16:54 UTC by Swastyy

#### Description of Change

#### References

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-21 19:31 UTC, Panquesito7 requested changes
Great work, @Swastyy! 😄
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C/actions

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + * @file floyd_cycle_detection_algorithm.c
```suggestion
 * @file
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +#include <stdio.h>
Please add a one-line description of what the library/header is for (**see the example below**).

```c
#include <stdio.h>      /// for IO operations
#include <assert.h>    /// for assert
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + * @brief The main function implements search algorithm
```suggestion
 * @brief The main function implements the search algorithm
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + */
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +void test()
```suggestion
static void test()
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + * @brief Main function
```suggestion
 * @brief Main function
 * @returns 0 on exit
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + */
```suggestion
 */

```

2021-07-21 19:31 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +int duplicateNumber(const int *in_arr, size_t n)
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. **Requires adding the `inttypes.h` library.** Check other parts of the code ([reference](https://en.cppreference.com/w/c/types/integer)). 🙂

2021-07-25 17:59 UTC, Panquesito7 requested changes

2021-07-25 17:59 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + */
```suggestion
 */
 
```

2021-07-25 17:59 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    uint32_t hare = in_arr[0];  // variable hare is used for shorter jumps in the array
```suggestion
    uint32_t tortoise = in_arr[0];  ///< variable tortoise is used for the longer
                                    ///< jumps in the array
    uint32_t hare = in_arr[0];  ///< variable hare is used for shorter jumps in the array
```

2021-07-25 17:59 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-07-25 17:59 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-07-25 18:27 UTC, Panquesito7 requested changes

2021-07-25 18:27 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + * Given an array of integers containing 'n + 1' integers, where each
```suggestion
 * Given an array of integers containing `n + 1` integers, where each
```

2021-07-25 18:27 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + * @param n size of array
```suggestion
 * @param n size of the array
```

2021-07-25 18:27 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    printf("passed\n");
Please consider adding some documentation in this part of the code.

2021-07-25 18:27 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> + */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-07-25 18:27 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-07-27 18:15 UTC, Panquesito7 requested changes

2021-07-27 18:15 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    return tortoise;
Please add a bit of documentation of what this code does.

2021-07-27 18:15 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-07-28 18:14 UTC, Panquesito7 reviewed
It's just to accept this suggestion, and you're done! 😄

2021-07-28 18:14 UTC, Panquesito7 commented on searching/floyd_cycle_detection_algorithm.c
> +    printf("Test 1.... ");
```suggestion
    printf("1st test... ");
```

2021-07-28 18:47 UTC, Swastyy commented
> It's just to accept this suggestion, and you're done! 😄

Done

2021-07-28 18:50 UTC, Panquesito7 approved these changes
Amazing work, congratulations, @Swastyy! Thank you for your continued contributions to our community! 😄👍🎉

2021-07-29 04:45 UTC, mishraabhinn requested changes

2021-07-29 04:45 UTC, mishraabhinn commented on searching/floyd_cycle_detection_algorithm.c
> +    if (n == 0 || n == 1) {  // to find duplicate in an array its size should be atleast 2
```suggestion
    if (n <= 1) {  // to find duplicate in an array its size should be atleast 2
```

2021-07-29 16:33 UTC, Panquesito7 approved these changes

2021-07-29 16:46 UTC, mishraabhinn approved these changes

2021-07-29 17:40 UTC, merged