feat: TCP Client Server Half Duplex Communication
TheAlgorithms/C pull request #853
Opened 2021-08-27 05:17 UTC by NVombat

#### Description of Change

Added the server and client code for half duplex TCP communication. Ran the code to make sure it compiles and runs successfully. Commented the code and followed contributing guidelines.

#### References

Implements Half Duplex Communication for #852 

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-08-28 15:36 UTC, NVombat commented
Is the last commit i made fine ?? I documented each part of the code carefully so every line and function is explained

2021-08-30 16:56 UTC, Panquesito7 requested changes

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> + * @see tcp_half_duplex_client.c
```suggestion
 * @see tcp_half_duplex_server.c
```

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> +/* MAIN DRIVER CODE */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> +*/
```suggestion
/**
 * @brief Utility function used to print an error message to `stderr`.
 * It prints `str` and an implementation-defined error
 * message corresponding to the global variable `errno`.
 * @returns void
 */
```

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +// Imports
```suggestion
```

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +*/
```suggestion
/**
 * @brief Utility function used to print an error message to `stderr`.
 * It prints `str` and an implementation-defined error
 * message corresponding to the global variable `errno`.
 * @returns void
 */
```

2021-08-30 16:56 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +/* MAIN DRIVER CODE */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-08-30 17:59 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> +// Imports
```suggestion
```

2021-08-30 17:59 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +// Imports
```suggestion
```

2021-08-31 00:16 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> + * @author [NVombat](https://github.com/NVombat)
```suggestion
 * @author [Nikhill Vombatkere](https://github.com/NVombat)
```

2021-08-31 00:16 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> + * @author [NVombat](https://github.com/NVombat)
```suggestion
 * @author [Nikhill Vombatkere](https://github.com/NVombat)
```

2021-08-31 15:44 UTC, NVombat commented
Are there any other changes that need to be made ?

2021-08-31 16:45 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> +                                // data for communication
```suggestion
    int sockfd;  ///< socket descriptors - Like file handles but for sockets
    struct sockaddr_in
        server_addr;  ///< basic structures for all syscalls and functions that
                      /// deal with internet addresses. Structures for handling
                      /// internet addresses
    char serverResponse[10000],
        clientResponse[10000];  ///< Character arrays to read and store string
                                ///< data for communication
```

2021-08-31 16:45 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +                      // internet addresses
```suggestion
    int sockfd, conn;  ///< socket descriptors - Like file handles but for sockets
    char server_msg[10000],
        client_msg[10000];  ///< character arrays to read and store string data
                            /// for communication
    struct sockaddr_in server_addr,
        client_addr;  ///< asic structures for all syscalls and functions that
                      /// deal with internet addresses. Structures for handling
                      /// internet addresses
```

2021-08-31 17:01 UTC, NVombat commented
I updated all comment formatting to be uniform.

2021-09-01 00:17 UTC, Panquesito7 commented on client_server/tcp_half_duplex_client.c
> +        error();
```suggestion
    if ((sockfd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        error();
    }
```

2021-09-01 00:17 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +                  /// socket wasnt created
```suggestion
    if ((sockfd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        error();  ///< Error if the socket descriptor has a value lower than 0 -
                  /// socket wasnt created
    }
```

2021-09-01 00:17 UTC, Panquesito7 commented on client_server/tcp_half_duplex_server.c
> +        error();  /// If binding is unsuccessful
```suggestion
    if (bind(sockfd, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0) {
        error();  /// If binding is unsuccessful
    }
```

2021-09-01 18:11 UTC, NVombat commented on client_server/tcp_half_duplex_client.c
> +    int sockfd;  ///< socket descriptors - Like file handles but for sockets
Okay i will look into this and make the change.

2021-09-01 19:24 UTC, Panquesito7 approved these changes
Amazing work, @NVombat! It's been great to be your first contribution here! We hope you keep contributing! 😄👍🎉

2021-09-01 19:32 UTC, NVombat commented
Thank you! Will contribute more for sure!

2021-09-02 04:02 UTC, NVombat commented
Just wanted to know - By when will this get merged??

2021-09-07 01:43 UTC, Panquesito7 commented
@amino19, would you like to review this PR? Thanks. 🙂

@ayaankhan98 and @mishraabhinn, please wait until @amino19 reviews this PR.
They're practicing with us and learning to review PRs with us. 🙂

2021-09-07 12:09 UTC, ayaankhan98 approved these changes
LGTM!

2021-09-07 15:22 UTC, amino19 approved these changes
@NVombat: Thanks for your contributions in **The Algorithms**!
LGTM! :partying_face: 

@Panquesito7: Pl take this to your end! : )

2021-09-07 15:54 UTC, merged