feat: add G.711 a-law algorithm
TheAlgorithms/C pull request #858
Opened 2021-09-25 12:12 UTC by HiSunzhenliang

#### Description of Change
1. add G.711 a-law algorithm
2. add audio/

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-09-27 01:52 UTC, HiSunzhenliang commented
Please review this and let me know if it needs to be fixed @Panquesito7
Thanks.

2021-09-27 02:07 UTC, Panquesito7 requested changes
Woah, awesome work! 👀🚀

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> + * @see audio/alaw.c
I think this is used when there are two or more similar files, so I don't think this is needed here. 🙂
```suggestion
```

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> + * https://en.wikipedia.org/wiki/G.711
```suggestion
```

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> + * @brief A-law algorithm for encoding and decoding (16bit pcm <=> a-law).
```suggestion
 * @brief A-law algorithm for encoding and decoding (16bit pcm <=> a-law).
 * This is the implementation of [G.711](https://en.wikipedia.org/wiki/G.711) in C++
```

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +#include <stdlib.h>
Please add a one-line description of what the library/header is for (**see the example below**).

```c
#include <stdlib.h>     /// for IO operations
#include <assert.h>    /// for assert
```

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +int main(int argc, char *argv[])
```suggestion
/**
 * @brief Main function
 * @param argc commandline argument count (ignored)
 * @param argv commandline array of arguments (ignored)
 * @returns 0 on exit
 */
int main(int argc, char *argv[])
```

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +    for (int i = 0; i < LEN; i++)
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). Requires adding the `inttypes.h` header. **Let us know if you need any help in our [Discord server](https://discord.gg/c7MnfGFGa6)**. 🙂

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +    }
Please add a bit of documentation of what this code does here.

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +    printf("\n");
Please add a bit of documentation of what this code does here.

2021-09-27 02:07 UTC, Panquesito7 commented on audio/alaw.c
> +        *out++ = alaw ^ 0xD5;
Please add a bit of documentation of what this code does here.

2021-09-27 06:37 UTC, HiSunzhenliang commented
Thanks for reviewing. I made some changes and submitted it again.

2021-09-28 02:31 UTC, Panquesito7 commented on audio/alaw.c
> + * @brief A-law algorithm for encoding and decoding (16bit pcm <=> a-law).
> Sorry, I can not see the problem here. Can you be more specific？Thanks.

Check line 5 in the suggestion. I hope that helps. 🙂

2021-09-28 03:07 UTC, HiSunzhenliang commented on audio/alaw.c
> + * @brief A-law algorithm for encoding and decoding (16bit pcm <=> a-law).
I already added `This is the implementation of [G.711](https://en.wikipedia.org/wiki/G.711) in C.` at line 5. The only difference is `...in C++` in the suggestion from my comment `...in C`. And this is C code right? So I am quite confused. :confounded:

2021-09-28 03:12 UTC, Panquesito7 commented on audio/alaw.c
> + * @brief A-law algorithm for encoding and decoding (16bit pcm <=> a-law).
Ahh, sorry! I modified the suggestion. Great catch! 😅

2021-09-28 03:31 UTC, Panquesito7 requested changes
Almost there! 😄

2021-09-28 03:31 UTC, Panquesito7 commented on audio/alaw.c
> +
Please add self-test implementations of your code to ensure it runs properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) for how to make it properly).

2021-09-28 17:28 UTC, Panquesito7 commented on audio/alaw.c
> +    int32_t mask;
You may want to initialize these variables to zero.
```suggestion
    uint8_t alaw = 0;
    int16_t pcm = 0;
    int32_t sign = 0;
    int32_t abcd = 0;
    int32_t eee = 0;
    int32_t mask = 0;
```

2021-09-28 17:28 UTC, Panquesito7 commented on audio/alaw.c
> +    int32_t eee;
Same here.
```suggestion
    uint8_t alaw = 0;
    int32_t pcm = 0;
    int32_t sign = 0;
    int32_t eee = 0;
```

2021-10-03 01:29 UTC, Panquesito7 reviewed
Almost there; great work! 🚀

2021-10-03 01:29 UTC, Panquesito7 commented on audio/alaw.c
> +    test(pcm, coded, decoded, LEN);
```suggestion
    test(pcm, coded, decoded, LEN);  // run self-test implementations
```

2021-10-03 17:19 UTC, Panquesito7 approved these changes
Awesome work! It's been great for your first contribution here! We hope you keep contributing. Thanks! 😄👍🎉

2021-10-03 17:54 UTC, amino19 approved these changes

2021-10-03 18:00 UTC, mishraabhinn approved these changes

2021-10-03 18:15 UTC, ayaankhan98 approved these changes
LGTM :+1:

2021-10-03 18:16 UTC, merged

2021-10-03 18:18 UTC, Panquesito7 commented
Thanks for reviewing, folks! 😄