Add stale workflow
TheAlgorithms/C pull request #860
Opened 2021-09-30 18:16 UTC by siriak

Add stale workflow that'll close old issues/PRs

2021-10-03 01:36 UTC, Panquesito7 requested changes

2021-10-03 01:36 UTC, Panquesito7 commented on .github/workflows/stale.yml
> +          close-issue-message: 'Please ping one of the maintainers once you add more information and updates here. If this is not the case and you need some help, feel free to ask for help in our [Gi
```suggestion
          close-issue-message: 'Please ping one of the maintainers once you add more information and updates here. If this is not the case and you need some help, feel free to ask for help in our [Gitter](https://gitter.im/TheAlgorithms) channel or our [Discord server](https://discord.gg/c7MnfGFGa6). Thank you for your contributions!'
```

2021-10-03 01:36 UTC, Panquesito7 commented on .github/workflows/stale.yml
> +          close-pr-message: 'Please ping one of the maintainers once you commit the changes requested or make improvements on the code. If this is not the case and you need some help, feel free to as
```suggestion
          close-pr-message: 'Please ping one of the maintainers once you commit the changes requested or make improvements on the code. If this is not the case and you need some help, feel free to ask for help in our [Gitter](https://gitter.im/TheAlgorithms) channel or our [Discord server](https://discord.gg/c7MnfGFGa6). Thank you for your contributions!'
```

2021-10-03 20:03 UTC, Panquesito7 approved these changes
Thanks! 😄

2021-10-04 17:00 UTC, siriak commented
Are we waiting on 1 more review? I cannot merge myself here

2021-10-04 20:43 UTC, Panquesito7 commented
> Are we waiting on 1 more review? I cannot merge myself here

Oops, I forgot to merge 🤦‍♂️ sorry. Merging now.

2021-10-04 20:44 UTC, merged