Added a Vector implementation in data structures.
TheAlgorithms/C pull request #977
Opened 2022-10-02 10:15 UTC by KILLinefficiency

#### Description of Change
Added an implementation of Vector (like std::vector in C++) written in C in the Data Structures directory.

#### References

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Hey @Panquesito7 ! Can you please review this PR? If there are any changes required please let me know and I'll implement them.

Also it's be great if you could add a ``hactoberfest-accepted`` tag to this PR.
Thank You!

2022-10-03 16:35 UTC, KILLinefficiency commented
Hello @Panquesito7, can I get a review?

2022-10-04 11:56 UTC, KILLinefficiency commented
Hello @Panquesito7, can you give this PR a ``hacktoberfest-accepted`` tag?

2022-10-04 16:30 UTC, Panquesito7 commented on data_structures/vector.c
> +#include <stdlib.h>    /** for malloc() and free() */
```suggestion
#include <stdio.h>     /// for IO operations
#include <stdlib.h>    /// for malloc() and free() 
```

2022-10-04 16:30 UTC, Panquesito7 commented on data_structures/vector.c
> +    int* contents;     /** the internal array itself. */
```suggestion
    int len;           ///< contains the length of the vector
    int current;       ///< holds the current item
    int* contents;     ///< the internal array itself
```

2022-10-04 16:30 UTC, Panquesito7 commented on data_structures/vector.c
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2022-10-04 17:04 UTC, KILLinefficiency commented
@Panquesito7 Done.

2022-10-05 02:31 UTC, Panquesito7 requested changes
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord). 😃

2022-10-06 19:24 UTC, KILLinefficiency commented
@Panquesito7 I added the tests.

2022-10-08 20:03 UTC, KILLinefficiency commented
@Panquesito7 Please review.

2022-10-12 18:23 UTC, KILLinefficiency commented
@Panquesito7 Please review.

2022-10-18 18:00 UTC, KILLinefficiency commented
@Panquesito7 Can you please review?

2022-11-08 16:42 UTC, Panquesito7 approved these changes
Amazing work! Thanks. 🚀
There are a few pending things to change. I will make another PR.

2022-11-08 17:06 UTC, tjgurwara99 approved these changes
LGTM

2022-11-08 21:18 UTC, merged