feat: Add run length encoding
TheAlgorithms/C pull request #983
Opened 2022-10-02 15:59 UTC by serturx

#### Description of Change

This pr adds the run-length encoding algorithm

#### References
https://en.wikipedia.org/wiki/Run-length_encoding

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-02 16:07 UTC, Panquesito7 requested changes
Great work! 🚀
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/serturx/C/actions

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> + * @file run_length_encoding.c
It's best not to include the name, otherwise, you'd have to include the full directory.
```suggestion
 * @file
```

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> + * @brief Encode a null terminated string using [Run-length encoding](https://en.wikipedia.org/wiki/Run-length_encoding)
Provide a detailed description explaining the algorithm, how it works, etc..

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +#include <assert.h>
Please add a one-line description of what the library/header is for (**see the example below**).

```c
#include <stdio.h>     /// for IO operations
#include <assert.h>    /// for assert
```

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +    printf("Tests passed.");
```suggestion
    printf("All tests have passed!\n");
```

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +    test();
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
    test();  // run self-test implementations
```

2022-10-02 16:07 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-03 08:31 UTC, serturx commented
Thanks for the review! I've addressed all issues and enabled github actions.

2022-10-05 02:26 UTC, Panquesito7 reviewed
Almost there! 😄

2022-10-05 02:26 UTC, Panquesito7 commented on misc/run_length_encoding.c
> + * @section Description
```suggestion
 * @details
```

2022-10-05 02:26 UTC, Panquesito7 commented on misc/run_length_encoding.c
> +#include <string.h> ///for string functions
```suggestion
#include <stdio.h>  /// for IO operations
#include <string.h> /// for string functions
```

2022-10-05 16:34 UTC, serturx commented
Thanks again, I've added your suggestions :)

2022-10-10 20:40 UTC, Panquesito7 approved these changes
Great work! Thanks. 🚀

2022-10-12 14:46 UTC, kvedala approved these changes
👍

2022-10-12 14:48 UTC, merged